### ISSUE TITLE
Error while running the sample file

### ISSUE THREAD

**Issue by pidugusundeep** [theasci/extendscript-logger#2]
here is the error which i get when i try to run the below code
```
var Global = Global || {};
Global.rootPath = new File($.fileName).parent;
$.evalFile(Global.rootPath + '/node_modules/extendscript-logger/index.jsx');
var Glogal.logger = new Logger('/log/test.log', 'DEBUG');


Glogal.logger.debug('Debug message');
Glogal.logger.info([1, "Random string"]);
Glogal.logger.notice({foo:"bar"});
Glogal.logger.warn("Danger, Will Robinson!");
Glogal.logger.error("Crap! Something went wrong.");
Glogal.logger.critical("DEFCON 1! Seek shelter.");
```

![Screenshot 2020-04-28 at 2 00 44 AM](https://user-images.githubusercontent.com/10946649/80417865-18effc00-88f4-11ea-816e-15c6b50152ee.png)

Please help me fix this.

**Comment by shawnpyle** [comment]
Glogal should have been Global. This has been fixed in https://github.com/theasci/extendscript-logger/commit/a15f6747e437f9c266046a6a4e0e07bbd90fcda1

**Comment by pidugusundeep** [comment]
It still shows the same error
```
var Global = Global || {};
Global.rootPath = new File($.fileName).parent;
$.evalFile(Global.rootPath + '/node_modules/extendscript-logger/index.jsx');
var Global.logger = new Logger(Global.rootPath+'/log/test.log', 'DEBUG')


Global.logger.debug('Debug message');
Global.logger.info([1, "Random string"]);
Global.logger.notice({foo:"bar"});
Global.logger.warn("Danger, Will Robinson!");
Global.logger.error("Crap! Something went wrong.");
Global.logger.critical("DEFCON 1! Seek shelter.");
```
![Screenshot 2020-04-28 at 9 43 32 AM](https://user-images.githubusercontent.com/10946649/80446541-bbc86a80-8934-11ea-8487-0a8569ac04e5.png)
